version: "3.5"

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  queue:
    image: rabbitmq:3.8.1

  b2flow:
    image: b2flow
    build:
      context: ./
      dockerfile: Dockerfile

  webapp:
    image: b2flow
    command: webapp
    ports:
      - 3000:3000
    links:
      - database
      - queue
    depends_on:
      - b2flow
      - database
      - queue
    environment:
      RAILS_ENV: production
      B2FLOW__HOSTNAME: localhost:3000
      B2FLOW__TOKEN_SECRET: abc123
      B2FLOW__QUEUE__NEW_JOBS: jobs
      B2FLOW__RABBIT__URI: redis://queue:6372/0
      B2FLOW__DB__URI: postgres://postgres:password@database:5432/b2flow?encoding=utf-8&pool=5
      B2FLOW__LOGLEVEL: info

  scheduler:
    image: b2flow
    command: scheduler
    links:
      - database
      - queue
    depends_on:
      - b2flow
      - database
      - queue
    environment:
      RAILS_ENV: production
      B2FLOW__HOSTNAME: localhost:3000
      B2FLOW__QUEUE__NEW_JOBS: jobs
      B2FLOW__RABBIT__URI: redis://queue:6372/0
      B2FLOW__DB__URI: postgres://postgres:password@database:5432/b2flow?encoding=utf-8&pool=5
      B2FLOW__LOGLEVEL: info


