version: "3.5"

volumes:
  mongo-db:

services:
  database:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

  webapp:
    image: allanbatista/b2flow
    command: webapp
    restart: unless-stopped
    ports:
      - 80:3000
    links:
      - database
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      B2FLOW__TOKEN_SECRET: abc123
      B2FLOW__DATABASE__URI: mongodb://mongo:password@database:27017/b2flow?authSource=admin
      B2FLOW__LOGLEVEL: info