version: "3.5"

volumes:
  mongo-db:
  redis-db:

services:
  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-db:/data
