version: '3.1'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  queue:
    image: rabbitmq:3.8.1-alpine
    ports:
      - 5672:5672
      - 15672:15672