version: "3.5"

volumes:
  mongo-db:
  redis-db:

services:
  mongodb:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-db:/data

  webapp:
    image: allanbatista/b2flow
    restart: unless-stopped
    ports:
      - 80:3000
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    environment:
      RAILS_ENV: development
      B2FLOW__TOKEN_SECRET: abc123
      B2FLOW__DATABASE__URI: mongodb://mongo:password@database:27017/b2flow?authSource=admin
      B2FLOW__LOGLEVEL: info
      B2FLOW__KUBERNETES__URI: http://localhost:8080/api
      B2FLOW__KUBERNETES__VERSION: v1
      B2FLOW__KUBERNETES__USERNAME: admin
      B2FLOW__KUBERNETES__PASSWORD: password
      B2FLOW__STORAGE__TYPE: local
      B2FLOW__STORAGE__ACCESS_KEY_ID: ""
      B2FLOW__STORAGE__SECRET_KEY_ID: ""
      B2FLOW__STORAGE__REGION: ""
      B2FLOW__STORAGE__BUCKET: ""
      B2FLOW__STORAGE__PREFIX: ""
      B2FLOW__SIDEKIQ__REDIS_URL: redis://redis:6379/0