---
default: &default
  B2FLOW__TOKEN_SECRET: oUyCzW5GnSs9p4g2CdBQHX4kK1lXZKNMAetaRQftibwYClWx8q5SHRkW1MNbACr707ag1m7RxdQvgPdyYS9GtM5otJ9mDURRjghvIzhk9KGLU6rLHT1wZC152K0F7EcUdslhV7hFn4mfH90yhi4fClR0vMWknH9Q0MQBlbLhOwaOScHYNCHFWa35ZujOaxRMple9FUCLqJc5xzX6GnDQGyrTcDH6aYro7rYn89Nyf8hepe2WThRLzIQLNbEtS5f3
  B2FLOW__DATABASE__URI: ""
  B2FLOW__LOGLEVEL: info
  B2FLOW__STORAGE__TYPE: local
  B2FLOW__STORAGE__S3__ACCESS_KEY_ID: ""
  B2FLOW__STORAGE__S3__SECRET_KEY_ID: ""
  B2FLOW__STORAGE__S3__REGION: ""
  B2FLOW__STORAGE__S3__BUCKET: ""
  B2FLOW__STORAGE__S3__PREFIX: ""
  B2FLOW__KUBERNETES__URI: http://localhost:8080/api
  B2FLOW__KUBERNETES__VERSION: v1
  B2FLOW__KUBERNETES__USERNAME: admin
  B2FLOW__KUBERNETES__PASSWORD: password
test:
  <<: *default
  B2FLOW__DATABASE__URI: mongodb://mongo:password@localhost:27017/b2flow_test?authSource=admin
  B2FLOW__STORAGE__TYPE: test
  B2FLOW__BROAKER__BATCH_SIZE: 1
development:
  <<: *default
  B2FLOW__DATABASE__URI: mongodb://mongo:password@localhost:27017/b2flow_development?authSource=admin
  B2FLOW__LOGLEVEL: debug
  B2FLOW__STORAGE__TYPE: local
production:
  <<: *default
  B2FLOW__LOGLEVEL: info
