test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= AppConfig.B2FLOW__STORAGE__S3__ACCESS_KEY_ID %>
  secret_access_key: <%= AppConfig.B2FLOW__STORAGE__S3__SECRET_KEY_ID %>
  region: <%= AppConfig.B2FLOW__STORAGE__S3__REGION %>
  bucket: <%= AppConfig.B2FLOW__STORAGE__S3__BUCKET %>